# Generated by Django 3.1.7 on 2021-03-17 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='FicheRecquisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantiservie', models.CharField(max_length=15)),
                ('dateFiche', models.DateField()),
                ('gestionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FicheDemande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Poche', models.IntegerField()),
                ('docteur', models.CharField(max_length=20)),
                ('nomReceveur', models.CharField(max_length=40)),
                ('age', models.PositiveIntegerField()),
                ('genre', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=20)),
                ('lieu_Naissance', models.CharField(max_length=20)),
                ('motif_Transfusion', models.TextField()),
                ('dateFiche', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', 'Accepter'), ('0', 'Refuse')], default='En Attente', max_length=10)),
                ('service_Demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiches.service')),
                ('visiteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BonExpedetion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantiteExpedier', models.FloatField()),
                ('prixUnit', models.PositiveIntegerField()),
                ('observation', models.TextField(max_length=2000)),
                ('dateBon', models.DateField()),
                ('fiche_recqui', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fiches.ficherecquisition')),
                ('gestionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
