# Generated by Django 3.1.7 on 2021-03-15 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=200)),
                ('date_donation', models.DateTimeField(auto_now_add=True)),
                ('nature_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default='0', null=True)),
                ('quantite_recue', models.IntegerField(blank=True, default='0', null=True)),
                ('recue_par', models.CharField(blank=True, max_length=50, null=True)),
                ('quantite_servie', models.IntegerField(blank=True, default='0', null=True)),
                ('servie_par', models.CharField(blank=True, max_length=50, null=True)),
                ('servie_a', models.CharField(blank=True, max_length=50, null=True)),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('creer_par', models.CharField(blank=True, max_length=50, null=True)),
                ('changer_niveau_stock', models.IntegerField(blank=True, default='0', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='produits.categorie')),
                ('nom_produit', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default='0', null=True)),
                ('quantite_recue', models.IntegerField(blank=True, default='0', null=True)),
                ('recue_par', models.CharField(blank=True, max_length=50, null=True)),
                ('quantite_servie', models.IntegerField(blank=True, default='0', null=True)),
                ('servie_par', models.CharField(blank=True, max_length=50, null=True)),
                ('servie_a', models.CharField(blank=True, max_length=50, null=True)),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('creer_par', models.CharField(blank=True, max_length=50, null=True)),
                ('changer_niveau_stock', models.IntegerField(blank=True, default='0', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dernier_misajour', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='produits.categorie')),
                ('nom_produit', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
            ],
        ),
    ]
