# Generated by Django 3.1.7 on 2021-03-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='nom_produit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='nom_produit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
