# Generated by Django 3.1.7 on 2021-03-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_auto_20210315_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='nom_produit',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('A', 'A'), ('B+', 'B+'), ('B-', 'B-'), ('B', 'B'), ('O+', 'O+'), ('O-', 'O-'), ('O', 'O')], max_length=15),
        ),
    ]
