# Generated by Django 3.1.7 on 2021-03-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_auto_20210318_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doneur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('bloodgroup', models.CharField(max_length=10)),
                ('adresse', models.CharField(max_length=40)),
                ('Tel', models.CharField(max_length=20)),
            ],
        ),
    ]
