# Generated by Django 3.1.7 on 2021-03-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_doneur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doneur',
            name='bloodgroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('A', 'A'), ('B+', 'B+'), ('B-', 'B-'), ('B', 'B'), ('O+', 'O+'), ('O-', 'O-'), ('O', 'O')], max_length=15),
        ),
    ]
