# Generated by Django 3.1.7 on 2021-03-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0005_auto_20210318_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='doneur',
            name='age',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doneur',
            name='genre',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default=2, max_length=15),
            preserve_default=False,
        ),
    ]
