# Generated by Django 3.1.7 on 2021-03-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0006_auto_20210318_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doneur',
            name='adresse',
        ),
        migrations.AddField(
            model_name='doneur',
            name='commune',
            field=models.CharField(choices=[('Muha', 'Muha'), ('Ntahangwa', 'Ntahangwa'), ('Mukaza', 'Mukaza')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doneur',
            name='zone',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
