# Generated by Django 3.1.7 on 2021-03-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0007_auto_20210318_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='nom_produit',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('A', 'A'), ('B+', 'B+'), ('B-', 'B-'), ('B', 'B'), ('O+', 'O+'), ('O-', 'O-'), ('O', 'O')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
