# Generated by Django 3.1.7 on 2021-03-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0008_auto_20210318_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date_donation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='date_donation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
