# Generated by Django 3.1.7 on 2021-03-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0011_auto_20210318_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='date_donation',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='produit',
            unique_together={('nature_produit', 'nom_produit', 'date_donation')},
        ),
    ]
