# Generated by Django 3.1.7 on 2021-03-17 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('idFacture', models.IntegerField(primary_key=True, serialize=False)),
                ('montant', models.FloatField()),
                ('dateFacture', models.DateField(auto_now_add=True)),
                ('gestionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Facturation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montantPaye', models.PositiveIntegerField()),
                ('dateFacturation', models.DateField(auto_now_add=True)),
                ('bonExpedetion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiches.bonexpedetion')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facture.facture')),
                ('gestionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
